export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'LOGIN_USER';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_TOOLTYPES_REQUEST = 'FETCH_TOOLTYPES_REQUEST';
export const FETCH_OPERATION_TYPES_REQUEST = 'FETCH_OPERATION_TYPES_REQUEST';
export const FETCH_TOOLTYPE_REQUEST = 'FETCH_TOOLTYPE_REQUEST';
export const FETCH_OPERATION_TYPE_REQUEST = 'FETCH_OPERATION_TYPE_REQUEST';
export const FETCH_TOOLTYPE_OPERATIONS_REQUEST =
  'FETCH_TOOLTYPE_OPERATIONS_REQUEST';
export const FETCH_TOOLS_REQUEST = 'FETCH_TOOLS_REQUEST';
export const FETCH_TOOL_REQUEST = 'FETCH_TOOL_REQUEST';
export const CLEAR_TOOL = 'CLEAR_TOOL';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const RESET_PRODUCT = 'RESET_PRODUCT';
